#!/usr/bin/env python3

import argparse
import re
from pathlib import Path


def parse_array_values(ctype: str, body: str):
    vals = []
    for part in body.replace("\n", " ").split(","):
        part = part.strip()
        if not part:
            continue
        if ctype == "float":
            vals.append(float(part.rstrip("f")))
        else:
            vals.append(int(part, 10))
    return vals


def load_header(path: Path):
    text = path.read_text()
    arrays = {}
    for m in re.finditer(
        r"const\s+(int8_t|int32_t|float|uint8_t)\s+(\w+)\[\d+\][^{]*=\s*\{(.*?)\};",
        text,
        re.S,
    ):
        ctype, name, body = m.groups()
        arrays[name] = parse_array_values(ctype, body)
    return text, arrays


def parse_layer(text: str, layer_idx: int):
    m = re.search(rf"\[{layer_idx}\]\s*=\s*\{{(.*?)\n\s*\}},", text, re.S)
    if not m:
        raise SystemExit(f"layer {layer_idx} not found in header")
    block = m.group(1)
    return dict(re.findall(r"\.(\w+)\s*=\s*([^,]+),", block))


def repack_tima8a32(weights, k_out, k_inner, w_stride, oc_block, k_block):
    if (k_out % oc_block) != 0:
        raise SystemExit("K_out must be a multiple of oc_block")
    if (k_block % 4) != 0:
        raise SystemExit("k_block must be a multiple of 4")
    k_padded = ((k_inner + k_block - 1) // k_block) * k_block
    if w_stride < k_padded:
        raise SystemExit("w_stride must cover the padded K dimension")

    out = []
    for ob in range(0, k_out, oc_block):
        for kb in range(0, k_padded, k_block):
            for k in range(0, k_block, 4):
                for oc in range(oc_block):
                    base = (ob + oc) * w_stride + kb + k
                    out.extend(weights[base:base + 4])
    return out


def repack_tl8(weights, k_out, k_inner, w_stride, oc_block, k_block, row_stride):
    if row_stride < oc_block:
        raise SystemExit("row_stride must cover one output block")
    if (k_out % oc_block) != 0:
        raise SystemExit("K_out must be a multiple of oc_block")
    k_padded = ((k_inner + k_block - 1) // k_block) * k_block
    if w_stride < k_padded:
        raise SystemExit("w_stride must cover the padded K dimension")

    out = []
    pad = [0] * (row_stride - oc_block)
    for ob in range(0, k_out, oc_block):
        for kb in range(0, k_padded, k_block):
            for k in range(k_block):
                row = []
                for oc in range(oc_block):
                    row.append(weights[(ob + oc) * w_stride + kb + k])
                out.extend(row)
                out.extend(pad)
    return out


def write_rows(f, values, row_len, indent="    ", suffix=""):
    for i in range(0, len(values), row_len):
        row = ", ".join(f"{v}{suffix}" for v in values[i:i + row_len])
        f.write(f"{indent}{row},\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--weights-header", required=True)
    ap.add_argument("--layer-index", type=int, required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--oc-block", type=int, default=16)
    ap.add_argument("--k-block", type=int, default=64)
    ap.add_argument("--tl8-row-stride", type=int, default=64)
    ap.add_argument("--emit-tima", action="store_true")
    args = ap.parse_args()

    text, arrays = load_header(Path(args.weights_header))
    layer = parse_layer(text, args.layer_index)

    k_out = int(layer["K_out"])
    k_h = int(layer["kH"])
    k_w = int(layer["kW"])
    k_inner = int(layer["K_inner"])
    w_stride = int(layer["w_stride"])
    k_padded = ((k_inner + args.k_block - 1) // args.k_block) * args.k_block

    weights = arrays[layer["w"]]
    bias = arrays[layer["b"]]
    scales = arrays[layer["s"]]
    tl8 = repack_tl8(
        weights,
        k_out,
        k_inner,
        w_stride,
        args.oc_block,
        args.k_block,
        args.tl8_row_stride,
    )
    tima = None
    if args.emit_tima:
        tima = repack_tima8a32(
            weights, k_out, k_inner, w_stride, args.oc_block, args.k_block
        )

    oc_blocks = k_out // args.oc_block
    guard = f"YOLOV5N_L{args.layer_index}_TENSOR_WEIGHTS_H"

    with open(args.out, "w") as f:
        f.write("/* AUTO-GENERATED by tools/gen_yolo_tensor_weights.py — DO NOT EDIT */\n")
        f.write(f"/* Source aggregate header: {Path(args.weights_header).resolve()} */\n")
        f.write(f"/* Source logical layer index: {args.layer_index} */\n")
        f.write(f"#ifndef {guard}\n#define {guard}\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define YOLOV5N_L{args.layer_index}_TENSOR_OC_BLOCK {args.oc_block}u\n")
        f.write(f"#define YOLOV5N_L{args.layer_index}_TENSOR_K_BLOCK {args.k_block}u\n")
        f.write(f"#define YOLOV5N_L{args.layer_index}_TENSOR_OC_BLOCKS {oc_blocks}u\n")
        f.write(
            f"#define YOLOV5N_L{args.layer_index}_TENSOR_K_INNER {k_inner}u\n"
        )
        f.write(
            f"#define YOLOV5N_L{args.layer_index}_TENSOR_K_PADDED {k_padded}u\n"
        )
        f.write(
            f"#define YOLOV5N_L{args.layer_index}_TENSOR_K_BLOCKS {k_padded // args.k_block}u\n"
        )
        f.write(
            f"#define YOLOV5N_L{args.layer_index}_TL8_ROW_STRIDE {args.tl8_row_stride}u\n"
        )
        f.write(
            f"#define YOLOV5N_L{args.layer_index}_TL8_BLOB_BYTES {len(tl8)}u\n"
        )
        if tima is not None:
            f.write(
                f"#define YOLOV5N_L{args.layer_index}_TIMA_BLOB_BYTES {len(tima)}u\n"
            )
        f.write(
            f"#define YOLOV5N_L{args.layer_index}_TENSOR_BLOB_BYTES "
            f"YOLOV5N_L{args.layer_index}_TL8_BLOB_BYTES\n\n"
        )

        if tima is not None:
            f.write(
                f"const int8_t yolov5n_l{args.layer_index}_tima_b[{len(tima)}] "
                "__attribute__((aligned(64), section(\".mram_data\"))) = {\n"
            )
            write_rows(f, tima, 32)
            f.write("};\n\n")

        f.write(
            f"const int8_t yolov5n_l{args.layer_index}_tl8_b[{len(tl8)}] "
            "__attribute__((aligned(64), section(\".mram_data\"))) = {\n"
        )
        write_rows(f, tl8, 32)
        f.write("};\n\n")

        f.write(
            f"const int32_t yolov5n_l{args.layer_index}_bias_blk[{oc_blocks}]"
            f"[{args.oc_block}] __attribute__((aligned(64), section(\".mram_data\"))) = {{\n"
        )
        for ob in range(oc_blocks):
            vals = bias[ob * args.oc_block:(ob + 1) * args.oc_block]
            row = ", ".join(str(v) for v in vals)
            f.write(f"    {{ {row} }},\n")
        f.write("};\n\n")

        f.write(
            f"const float yolov5n_l{args.layer_index}_scale_blk[{oc_blocks}]"
            f"[{args.oc_block}] __attribute__((aligned(64), section(\".mram_data\"))) = {{\n"
        )
        for ob in range(oc_blocks):
            vals = scales[ob * args.oc_block:(ob + 1) * args.oc_block]
            row = ", ".join(f"{v:.9g}f" for v in vals)
            f.write(f"    {{ {row} }},\n")
        f.write("};\n\n")

        f.write(f"#endif /* {guard} */\n")


if __name__ == "__main__":
    main()
